/*
Generated by npm run actiontypes
Using ../scripts/actiontypes.ts
Payload interfaces are kept in sync with Actions & Inputs defined in manifest.yml
*/
import type { CommonEvent } from "./forge/events";
import type { RovoContext } from "./rovo/action";
export interface CreatePagePayload extends CommonEvent {
  spaceId: string;
  parentId: string;
  title: string;
  content: string;
  status?: string;
  context: RovoContext;
}
export interface UpdatePagePayload extends CommonEvent {
  pageId: string;
  title: string;
  content: string;
  status?: string;
  context: RovoContext;
}
export interface AddCommentPayload extends CommonEvent {
  comment: string;
  pageId: string;
  context: RovoContext;
}
